# Copyright 2020 Openbase, Inc.
---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - vars_files/vcenter_info_vars.yml
  
  tasks:
    - name: run my script!
      command: python ./module_utils/sync_vars_to_tn.py
