# Copyright 2020 Openbase, Inc.
---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - vars_files/nsxt_info_vars.yml

  tasks:
    - name: Create IP Pools
      nsxt_ip_pools:
        hostname: "{{ nsx_node['hostname'] }}"
        username: "{{ nsx_node['nsx_username'] }}"
        password: "{{ nsx_node['nsx_password'] }}"
        validate_certs: "{{ nsx_node['validate_certs'] }}"
        display_name: "{{ item.display_name }}"
        subnets: "{{ item.subnets }}"
        state: "{{ state }}"
      with_items:
        - "{{ VTEP }}"
