# Copyright 2020 Openbase, Inc.
---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - vars_files/create_nsx_transport_vars.yml
    - vars_files/nsxt_info_vars.yml    

  tasks:
    - name: Create transport zone
      nsxt_transport_zones:
        hostname: "{{ nsx_node['hostname'] }}"
        username: "{{ nsx_node['nsx_username'] }}"
        password: "{{ nsx_node['nsx_password'] }}"
        validate_certs: "{{ nsx_node['validate_certs'] }}"
        resource_type: "TransportZone"
        display_name: "{{ item.display_name }}"
        description: "{{ item.description }}"
        transport_type: "{{ item.transport_type }}"
        host_switch_name: "{{ item.host_switch_name }}"
        state: "{{ state }}"

      with_items:
        - "{{ transport_zones }}"
