# Copyright 2020 Openbase, Inc.
---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - vars_files/create_esxi_transport_profiles_vars.yml
    - vars_files/nsxt_info_vars.yml    

  tasks:
    - name: Create Transport Two PNIC Node Profiles
      nsxt_transport_node_profiles:
        hostname: "{{ nsx_node['hostname'] }}"
        username: "{{ nsx_node['nsx_username'] }}"
        password: "{{ nsx_node['nsx_password'] }}"
        validate_certs: "{{ nsx_node['validate_certs'] }}"
        resource_type: TransportNodeProfile
        display_name: "{{ item.display_name }}"
        description: "{{ item.description }}"
        host_switch_spec:
          resource_type: StandardHostSwitchSpec
          host_switches: "{{ item.host_switches }}"
        transport_zone_endpoints: "{{item.transport_zone_endpoints}}"
        state: "{{state}}"
      with_items:
        - "{{ transport_node_profiles1 }}"
        - "{{ transport_node_profiles2 }}"
