# Copyright 2020 Openbase, Inc.
---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - vars_files/deploy_nsx_tn_vars1.yml
    - vars_files/nsxt_info_vars.yml    
    - vars_files/vcenter_info_vars.yml
  tasks:
    - name: Attach Transport node profile to cluster
      nsxt_transport_node_collections:
        hostname: "{{ nsx_node['hostname'] }}"
        username: "{{ nsx_node['nsx_username'] }}"
        password: "{{ nsx_node['nsx_password'] }}"
        validate_certs: "{{ nsx_node['validate_certs'] }}"
        display_name: "{{ item.display_name }}"
        resource_type: "TransportNodeCollection"
        description: "Transport Node Collections 1"
        compute_manager_name: "{{ item.compute_manager_name }}"
        cluster_name: "{{ item.cluster_name }}"
        transport_node_profile_name: "{{ item.transport_node_profile_name }}"
        state: "{{ state }}"
      with_items:
        - "{{ compute_managers2 }}"
        - "{{ compute_managers3 }}"
