# Copyright 2020 Openbase, Inc.
---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - vars_files/deploy_nsx_tn_vars1.yml
    - vars_files/nsxt_info_vars.yml    
    - vars_files/nsxt_info_vars.yml
  tasks:
    - name: Add edge cluster
      nsxt_edge_clusters:
        hostname: "{{ nsx_node['hostname'] }}"
        username: "{{ nsx_node['nsx_username'] }}"
        password: "{{ nsx_node['nsx_password'] }}"
        validate_certs: "{{ nsx_node['validate_certs'] }}"
        display_name: "{{ item.display_name }}"
        cluster_profile_bindings:
        - profile_id: "{{ item.cluster_profile_binding_id }}"
        members: "{{ item.members}}"
        state: "{{ state }}"
      with_items:
        - "{{ edge_clusters }}"
